name: PexBlock
main: com.battleasya.pexblock.PexBlock
version: 1.0.0
author: Dennie
website: http://battleasya.com
description: A simple anti-exploit extension for PermissionEx.
depend: [PermissionsEx]